import './globals.css'
import {Suspense} from "react"
import {Inter} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import Nav from './components/Nav'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'aleivc',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <ClerkProvider>
                <body className={inter.className}>
                    <Nav />
                <div>
                    {children}
                </div>
                </body>
            </ClerkProvider>
        </html>
    )
}